package com.example.foodcoma.database

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.foodcoma.model.FavoriteRecipeEntity
import com.example.foodcoma.model.Recipe
import com.example.foodcoma.model.RecipeShort

private const val strIngredientList = "strIngredient1, strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strIngredient16, strIngredient17, strIngredient18, strIngredient19, strIngredient20"
@Dao
interface RecipeDao {
    @Query("SELECT recipe_id FROM favorite_recipes")
    suspend fun getAllFavoriteIDs(): List<String>

    @Query("SELECT * FROM recipes LEFT JOIN favorite_recipes ON recipes.idMeal = favorite_recipes.recipe_id")
    //@Query("SELECT * FROM recipes WHERE idMeal IN (SELECT recipe_id FROM favorite_recipes)")      // use one of these
    suspend fun getAllFavorites(): List<Recipe>

    @Query("SELECT * FROM recipes WHERE idMeal = :recipeID")
    suspend fun getRecipeByID(recipeID: String): List<Recipe>

    @Query("SELECT * FROM recipes WHERE strMeal LIKE '%' || :query || '%'")     //TODO: autogenerated; check if works
    suspend fun searchRecipes(query: String): List<Recipe>

    @Query("SELECT idMeal, strMeal, strMealThumb FROM recipes WHERE :ingredient IN ($strIngredientList)")
    suspend fun getRecipeByIngredient(ingredient: String): List<RecipeShort>

    @Query("SELECT idMeal, strMeal, strMealThumb FROM recipes WHERE :category = strCategory")
    suspend fun getRecipeByCategory(category: String): List<RecipeShort>

    @Query("SELECT idMeal, strMeal, strMealThumb FROM recipes WHERE :area = strArea")
    suspend fun getRecipeByArea(area: String): List<RecipeShort>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertFavorite(favRecipe: FavoriteRecipeEntity)

    @Delete
    suspend fun deleteFavorite(favRecipe: FavoriteRecipeEntity)            // TODO: check how th @delete works


}